name: build os

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - oses/**

permissions:
  contents: read
  packages: write

jobs:
  push:
    name: "yolks:${{ matrix.oses }}"
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        oses:
          - debian

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Repository to lowercase
        id: lower-repo
        run: |
          echo "repository=${GITHUB_REPOSITORY_OWNER@L}" >> "$GITHUB_OUTPUT"

      - name: Set image tags
        id: tags
        run: |
          TAGS="ghcr.io/${{ steps.lower-repo.outputs.repository }}/yolks:${{ matrix.oses }}"
          if [ "${{ github.repository_owner }}" = "danios" ]; then
            TAGS="$TAGS,ghcr.io/danios/yolks:${{ matrix.oses }}"
          fi
          echo "tags=$TAGS" >> "$GITHUB_OUTPUT"

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.lower-repo.outputs.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: ./oses/${{ matrix.oses }}
          file: ./oses/${{ matrix.oses }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
